import type { ProductRow } from "@/types/commerce";

/** Small demo catalog when Supabase is empty — not a full fill, just enough to browse. */
const IMG = "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600";
const IMG2 = "https://images.unsplash.com/photo-1581092335397-9583eb92d232?w=600";
const IMG3 = "https://images.unsplash.com/photo-1558002038-1055907df827?w=600";

export const MOCK_PRODUCTS: ProductRow[] = [
  {
    id: "mock-1",
    title: "Tuya Zigbee Motion Sensor PIR",
    slug: "tuya-zigbee-pir",
    description: "Battery PIR motion sensor with Zigbee 3.0 mesh.",
    category: "Temperature Sensors",
    price_pkr: 1850,
    stock: 120,
    image_url: IMG2,
    manufacturer: "Tuya",
    color: "White",
    availability: "in_stock",
    discount_pct: 25,
    tags: ["sensor", "zigbee"],
    rating: 4.5,
    gallery_urls: [
      "https://images.unsplash.com/photo-1581092335397-9583eb92d232?w=600",
      "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=600",
    ],
    specs: { power: "3V (2× AAA)" },
  },
  {
    id: "mock-2",
    title: "Tuya Smart Wi-Fi Dome Camera 4MP",
    slug: "tuya-wifi-dome-4mp",
    description: "Indoor dome camera with night vision and app alerts.",
    category: "Smart Cameras",
    price_pkr: 8500,
    stock: 42,
    image_url: IMG3,
    manufacturer: "Tuya",
    color: "White",
    availability: "in_stock",
    discount_pct: 15,
    tags: ["camera", "wifi"],
    rating: 4.6,
    gallery_urls: [
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=600",
      "https://images.unsplash.com/photo-1551808525-51a94da548ce?w=600",
    ],
    specs: { power: "12V DC" },
  },
  {
    id: "mock-3",
    title: "Raspberry Pi 5 — 8GB",
    slug: "raspberry-pi-5-8gb",
    description: "Quad-core ARM Cortex-A76, 8GB RAM.",
    category: "Raspberry Pi",
    price_pkr: 32000,
    stock: 18,
    image_url: IMG,
    manufacturer: "Raspberry Pi",
    color: "Green",
    availability: "in_stock",
    discount_pct: 0,
    tags: ["sbc"],
    rating: 4.9,
    gallery_urls: [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600",
      "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=600",
    ],
    specs: { power: "5V 5A USB-C" },
  },
  {
    id: "mock-4",
    title: "ESP32-WROOM-32 DevKit",
    slug: "esp32-wroom-devkit",
    description: "Wi-Fi + BLE MCU for IoT prototyping.",
    category: "ESP32 / MCU Boards",
    price_pkr: 1450,
    stock: 200,
    image_url: IMG,
    manufacturer: "Espressif",
    color: "Black",
    availability: "in_stock",
    discount_pct: 20,
    tags: ["esp32"],
    rating: 4.8,
    gallery_urls: [],
    specs: {},
  },
  {
    id: "mock-5",
    title: "8-Channel Relay Module",
    slug: "relay-8ch-opto",
    description: "10A relay board with optocoupler isolation.",
    category: "Connectors",
    price_pkr: 1450,
    stock: 85,
    image_url: IMG,
    manufacturer: "Generic",
    color: "Blue",
    availability: "in_stock",
    discount_pct: 0,
    tags: ["relay"],
    rating: 4.5,
    gallery_urls: [],
    specs: {},
  },
  {
    id: "mock-6",
    title: "Siemens S7-1200 CPU 1214C",
    slug: "siemens-s7-1200",
    description: "Compact PLC for industrial automation.",
    category: "Programmable Logic Controller (PLC)",
    price_pkr: 145000,
    stock: 5,
    image_url: IMG,
    manufacturer: "Siemens",
    color: "Gray",
    availability: "in_stock",
    discount_pct: 0,
    tags: ["plc"],
    rating: 4.9,
    gallery_urls: [],
    specs: {},
    vendor_id: "demo-vendor",
  },
  {
    id: "mock-7",
    title: "Tuya Zigbee Gateway Hub Pro",
    slug: "tuya-zigbee-gateway-pro",
    description: "Zigbee 3.0 hub for up to 128 devices.",
    category: "Gateways",
    price_pkr: 7900,
    stock: 32,
    image_url: IMG3,
    manufacturer: "Tuya",
    color: "Black",
    availability: "in_stock",
    discount_pct: 12,
    tags: ["gateway"],
    rating: 4.7,
    gallery_urls: [],
    specs: {},
  },
  {
    id: "mock-8",
    title: "Creality Ender 3 V3 SE",
    slug: "creality-ender-3-v3",
    description: "Entry-level FDM 3D printer.",
    category: "3D Printer",
    price_pkr: 89000,
    stock: 8,
    image_url: IMG2,
    manufacturer: "Creality",
    color: "Black",
    availability: "in_stock",
    discount_pct: 8,
    tags: ["3d"],
    rating: 4.4,
    gallery_urls: [],
    specs: {},
  },
  {
    id: "mock-9",
    title: "UNI-T Digital Multimeter",
    slug: "uni-t-multimeter",
    description: "True RMS bench-friendly DMM.",
    category: "Multimeters",
    price_pkr: 12500,
    stock: 24,
    image_url: IMG,
    manufacturer: "UNI-T",
    color: "Yellow",
    availability: "in_stock",
    discount_pct: 5,
    tags: ["tool"],
    rating: 4.6,
    gallery_urls: [],
    specs: {},
  },
  {
    id: "mock-10",
    title: "NEMA 17 Stepper Motor",
    slug: "nema-17-stepper",
    description: "1.8° stepper for CNC and robotics.",
    category: "Motors",
    price_pkr: 3200,
    stock: 60,
    image_url: IMG2,
    manufacturer: "Generic",
    color: "Black",
    availability: "in_stock",
    discount_pct: 10,
    tags: ["motor"],
    rating: 4.3,
    gallery_urls: [],
    specs: {},
    vendor_id: "demo-vendor",
  },
  {
    id: "mock-11",
    title: "Mean Well 24V 10A PSU",
    slug: "meanwell-24v-10a",
    description: "Industrial DIN-rail power supply.",
    category: "DC Power Supplies",
    price_pkr: 9800,
    stock: 40,
    image_url: IMG,
    manufacturer: "MeanWell",
    color: "Silver",
    availability: "in_stock",
    discount_pct: 0,
    tags: ["psu"],
    rating: 4.7,
    gallery_urls: [],
    specs: {},
  },
  {
    id: "mock-12",
    title: "4-Gang Smart Wi-Fi Switch",
    slug: "wifi-switch-4gang",
    description: "Glass touch wall switch, neutral required.",
    category: "Smart Switch",
    price_pkr: 5400,
    stock: 55,
    image_url: IMG3,
    manufacturer: "Tuya",
    color: "Black",
    availability: "in_stock",
    discount_pct: 10,
    tags: ["switch"],
    rating: 4.5,
    gallery_urls: [],
    specs: {},
  },
];

export function getMockProductBySlug(slug: string) {
  return MOCK_PRODUCTS.find((p) => p.slug === slug) ?? null;
}

export const MOCK_PRODUCT_COUNT = MOCK_PRODUCTS.length;
